# Generated by Django 3.0.5 on 2020-04-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='calculate_worth',
            field=models.BooleanField(default=False),
        ),
    ]
