# Generated by Django 3.0.5 on 2020-04-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='item_worth',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='completed_date',
            field=models.DateField(),
        ),
    ]
