# Generated by Django 3.0.5 on 2020-04-16 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_items', '0002_auto_20200416_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
