# Generated by Django 3.0.5 on 2020-04-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_items', '0004_auto_20200416_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='item_name',
            field=models.CharField(max_length=500),
        ),
    ]
